compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: null
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 9
use_cpu: false
