data:
  train_files: data/URL/RL_stage/1_Stephen_King_RLReject/rl_rejection.json
  val_files: data/URL/RL_stage/1_Stephen_King_RLReject/rl_rejection.json
  prompt_key: prompt
  answer_key: solution
  val_prompt_key: prompt
  val_answer_key: solution
  image_key: images
  max_prompt_length: 512
  max_response_length: 1024
  rollout_batch_size: 512
  shuffle: true
  seed: 42
  max_pixels: 4194304
  min_pixels: 262144

algorithm:
  adv_estimator: grpo
  disable_kl: false
  use_kl_loss: true
  kl_penalty: low_var_kl
  kl_coef: 1.0e-2

worker:
  actor:
    global_batch_size: 128
    micro_batch_size_per_device_for_update: 4
    micro_batch_size_per_device_for_experience: 16
    max_grad_norm: 1.0
    padding_free: true
    ulysses_sequence_parallel_size: 1
    model:
      model_path: /mnt/usercache/huggingface/Meta-Llama-3-8B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: false
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      strategy: adamw  # {adamw, adamw_bf16}
      lr_warmup_ratio: 0.0
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
    offload:
      offload_params: true  # true: more CPU memory; false: more GPU memory
      offload_optimizer: true  # true: more CPU memory; false: more GPU memory
  critic:
    global_batch_size: 32
    padding_free: true
    ulysses_sequence_parallel_size: 1
    micro_batch_size_per_device_for_experience: 16
    micro_batch_size_per_device_for_update: 4
    model:
      model_path: /mnt/usercache/huggingface/Meta-Llama-3-8B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: false
      override_config:
        num_labels: 1
  rollout:
    temperature: 1.0
    n: 8
    gpu_memory_utilization: 0.4
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 1
    limit_images: 0
    val_override_config:
      temperature: 0.95
      n: 1
      top_p: 0.7
      top_k: 50
      num_beams: 1
      do_sample: false

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true  # true: more CPU memory; false: more GPU memory
      enable_rank0_init: true
    offload:
      offload_params: false

  reward:
    reward_type: function
    score_function: forget

trainer:
  total_episodes: 20
  logger: ["console", "wandb"]
  project_name: easy_r1
  experiment_name: llama3_8b_instruct
  n_gpus_per_node: 4
  nnodes: 1
  val_freq: 1
  val_before_train: true
  val_only: false # TODO: change to false
  val_generations_to_log: 20
  save_freq: -2
  save_checkpoint_path: null
  load_checkpoint_path: null
